GET http://localhost:3000/users/

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userEmail": "testUser10@email.com",
    "password": "Test Password",
    "userName": "Test User 4"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "userEmail": "testUser4@email.com",
    "password": "Test Password"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json
{
    "token": "Bearer d"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "token": "Bearer a68db25e3940becc2b7bfa5834085146560189d013b286552e010b38c038678a5aa7ec459a035b447eed105bdb5d83011d5fd7829d7061f5d6b6d1e7643efd9d"
}

###