GET http://localhost:3000/users/

###

GET http://localhost:3000/users/initialUser@email.com

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userEmail": "testUser2@email.com",
    "password": "Test Password",
    "userName": "Test User 4"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "password": "Test Password"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTUwNDE2Nn0.HJRQ2AQrJ9qk9Huf9FZaixUjpeYGziS07xzEPk4VpF4"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "email": "initialUser@email.com",
    "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJpbml0aWFsVXNlckBlbWFpbC5jb20iLCJ1c2VyTmFtZSI6IkluaXRpYWwgVXNlciIsImlhdCI6MTYzOTUwNDcwN30.zTASHCGode_memp_9dLOxw-BMPcEgS7GikJYditFTxE"
}

###